### ISSUE TITLE
Ejercicio 4 área de un triangulo. Problemas con el test unitario.

### ISSUE THREAD

**Issue by wotanCode** [4GeeksAcademy/master-python-programming-exercises#19]
El área de un triangulo se calcula multiplicando ambos lados divido entre dos, sin embargo al colocar el siguiente código no pasa el test.

```
#Complete the function to return the area of the triangle.
b = input("Size of B")
h = input("Size of H")

def area_of_triangle(arg1, arg2):
    #your code here, please remove the "None" 
    return (arg1*arg2)/2

# Testing your function
print(area_of_triangle(b, h))
```

**Comment by AbreuY** [comment]
Esto es porque a partir de python 3 el input devuelve un string. Debes convertir ese string a un entero usando la función int

```
b = int(input("Size of B"))
h = int(input("Size of H"))
```

Puedes obtener mas información acá [Input python](https://docs.python.org/3/library/functions.html#input)

**Comment by AbreuY** [comment]
Hi, @alesanchezr. You can consider closing this issue.
